version: '3.9'

services:

  postgres-db:
    container_name: postgres_db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
# Перед запуском отредактировать
      - /home/anton/Downloads/docker/pg:/var/lib/postgresql/data

  customer-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8585:8585"
    depends_on:
      - postgres-db
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/postgres
      - DB_USER=admin
      - DB_PASS=admin